# Generated by Django 4.0.2 on 2022-03-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='takencourse',
            field=models.CharField(blank=True, choices=[('빅데이터 프로젝트과정', '빅데이터 프로젝트과정'), ('AI 프로젝트과정', 'AI 프로젝트과정'), ('클라우드 프로젝트과정', '클라우드 프로젝트과정'), ('IOT 프로젝트과정', 'IOT 프로젝트과정')], max_length=20, null=True),
        ),
    ]
