# Generated by Django 4.0.2 on 2022-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cafe', 'Cafe'), ('FOOD', 'Food'), ('NOTEBOOK', 'Notebook')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('kakaourl', models.URLField()),
                ('pageurl', models.URLField()),
            ],
        ),
    ]
