# Generated by Django 4.0.2 on 2022-03-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('select', models.CharField(choices=[('2022년 강서구 빅데이터 활용 공모전', '2022년 강서구 빅데이터 활용 공모전'), ('2022년 노원구 빅데이터 활용 공모전', '2022년 노원구 빅데이터 활용 공모전')], max_length=80, null=True)),
                ('personnel', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.recruit')),
            ],
        ),
    ]
