# Generated by Django 4.0.2 on 2022-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='personnel',
            field=models.IntegerField(default=0),
        ),
    ]
