# Generated by Django 4.0.2 on 2022-03-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_recruit_select'),
        ('group', '0006_alter_recruit_select'),
    ]

    operations = [
    ]
