# Generated by Django 4.0.2 on 2022-03-12 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnaboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='like_users',
            field=models.ManyToManyField(related_name='like_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
