# Generated by Django 4.0.2 on 2022-03-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaboard', '0005_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
