# Generated by Django 4.0.2 on 2022-03-12 02:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('before', '모집중'), ('start', '도전시작'), ('finish', '도전종료')], default='before', max_length=8)),
                ('routine', models.CharField(choices=[('everyday', '매일'), ('weekend_only', '주말만'), ('5times_a_week', '월화수목금'), ('3times_a_week', '주3회'), ('twice_a_week', '주2회'), ('once_a_week', '주1회')], default='everyday', max_length=15)),
                ('num_of_auth_per_day', models.IntegerField(default=1)),
                ('date_start', models.DateField(default=datetime.datetime(2022, 3, 12, 2, 53, 15, 490169, tzinfo=utc))),
                ('date_finish', models.DateField(default=datetime.datetime(2022, 3, 19, 2, 53, 15, 490288, tzinfo=utc))),
                ('created', models.DateField()),
                ('modified', models.DateField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=150)),
                ('file', models.ImageField(upload_to='challenge_photo')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfauth', to='challenges.challenge')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
