# Generated by Django 4.0.2 on 2022-03-12 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 2, 53, 25, 304288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 2, 53, 25, 304102, tzinfo=utc)),
        ),
    ]
