# Generated by Django 4.0.2 on 2022-03-12 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_date_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='modified',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 6, 31, 31, 278425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 6, 31, 31, 278291, tzinfo=utc)),
        ),
    ]
