# Generated by Django 4.0.2 on 2022-03-12 07:08

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0004_alter_challenge_date_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ManyToManyField(blank=True, related_name='join', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 3, 19, 7, 8, 17, 584407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 7, 8, 17, 584290, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='challenger',
        ),
    ]
