# Generated by Django 4.0.2 on 2022-03-13 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challenge_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 7, 25, 53, 755441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 7, 25, 53, 755151, tzinfo=utc)),
        ),
    ]
