# Generated by Django 4.0.2 on 2022-03-13 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0009_alter_challenge_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenger',
            field=models.ManyToManyField(blank=True, related_name='challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 8, 24, 3, 977514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 8, 24, 3, 977368, tzinfo=utc)),
        ),
    ]
