# Generated by Django 4.0.2 on 2022-03-14 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_alter_challenge_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 3, 21, 7, 5, 6, 798482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 3, 14, 7, 5, 6, 798482, tzinfo=utc)),
        ),
    ]
