# Generated by Django 4.0.2 on 2022-03-14 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranker',
            name='ranker',
        ),
        migrations.AddField(
            model_name='ranker',
            name='ranker',
            field=models.ManyToManyField(related_name='ranking', to=settings.AUTH_USER_MODEL),
        ),
    ]
