# Generated by Django 4.0.2 on 2022-03-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_remove_ranker_ranker_ranker_ranker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranker',
            old_name='ranker',
            new_name='rankers',
        ),
    ]
